import { ICorridaRepository } from '../interfaces/ICorridaRepository';
import { Corrida } from '../../domain/entities/Corrida';
import { CorridaStatus } from '../../domain/valueObjects/CorridaStatus';

interface CreateCorridaDTO {
  usuarioId: number;
  origem: string;
  destino: string;
}

export class CreateCorridaUseCase {
  private corridaRepository: ICorridaRepository;

  constructor(corridaRepository: ICorridaRepository) {
    this.corridaRepository = corridaRepository;
  }

  public async execute(data: CreateCorridaDTO): Promise<Corrida> {
    const corrida = new Corrida(
      0, // ID will be generated by the database
      data.usuarioId,
      data.origem,
      data.destino,
      CorridaStatus.PENDENTE,
      new Date(),
      new Date()
    );

    return this.corridaRepository.create(corrida);
  }
}
